"""Add new field for avatar hash value

Revision ID: 457230694920
Revises: 39091d93af92
Create Date: 2024-11-09 18:56:26.569807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457230694920'
down_revision = '39091d93af92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###
