"""Add email column

Revision ID: 70403ff69e02
Revises: 22ba6d8fdade
Create Date: 2024-10-29 00:14:25.879314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70403ff69e02'
down_revision = '22ba6d8fdade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
